version: '2.1'
services:
  postgres:
    image: postgres:9.6-alpine
    container_name: jira_db
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_DB=jira
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./pg/data:/var/lib/postgresql/data
    ports:
      - 54321:5432
    restart: always


  jira:
    container_name: jira_srv
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
      - JVM_SUPPORT_RECOMMENDED_ARGS=-javaagent:/var/agent/atlassian-agent.jar
#      - JVM_MINIMUM_MEMORY=1g
#      - JVM_MAXIMUM_MEMORY=12g
#      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    volumes:
      - ./jira/conf/server.xml:/opt/atlassian/jira/conf/server.xml
      - ./jira/atlassian:/var/atlassian/application-data/jira
      - ./jira/agent:/var/agent
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
